### PR TITLE
Display the value of the buttons when clicked

### PR DESCRIPTION
**Pull request by chidinma-godwin**
I added a functionality to display the values of any button that is clicked. Please check if it's something you'll like to add

### CODE REVIEW

**Comment by ansdb** [comment]
Hi @chidinma-godwin I've checked your code for the `main.js` file, it's short and so useful I really like it, thank you so much for your contribution, but I'd like to say that it needs just a few lines of adjustments and additional code in the same time, to be complete and do all the work.

Here is what it needs to be more useful and complete:

###    for main.js file

- In line number `7` you should replace the assignment `=` operator with `+=`, because if we want to write 18 we click 1 then 8 so what's displayed after that process is just 8 that's why we need to replace `=` with `+=`. I hope you understand this point.
- The `C` Button couldn't work with the `+=` instead it'd work just fine with 
 the assignment operator `=`, because it's a `reset button` so everything in the `input-output-area` should be empty after pressing this button. I hope you understand this point as well.
- So to make the **last two points** work properly we need to add another conditional statement one for the `C` button and the other for the rest of buttons but not the _delete-the last-item-button_.
- Finally, just try to add all of that inside a function and name it in a descriptive way or name it just `inputVisualisation`.

###    for index.html file

- You just need to replace the class name for the `C` button with `reset-btn` because it's unique and has his own conditional statement.

**Please implement these changes I putted here as soon as possible, in order to be merged with my codebase**

Thanks again for your contribution.

**Comment by chidinma-godwin** [comment]
I've made the changes you requested, though I added them to an IIFE instead of a regular function, so I could invoke them immediately they're created.

 Let me know if there's any other changes you'll like to make.

**Comment by ansdb** [comment]
Thanks for the adjustments you made, you did fantastic work and I love the way the code is structured, everything is running smoothly and work properly now, but when I click somewhere in between buttons `undefined` is displayed on the `input-output-area`.
so we need to prevent that from happening by following the next steps, so, please:
###  main.js file
- Replace the _default_ with the _case condition_ with the "btn" to show up just the value of buttons because the default is everywhere not just the buttons and that's why we got `undefined` when we click elsewhere in between buttons, I hope you understand this point.

It will be like that `case "btn"`.

- We need to prevent **equality** (result button) **sign** to be displayed as well because the result button when clicked the **result of the calculation** should appear immediately on the screen, so just change the class name for `=` sign from `btn` to the `result-btn` instead.

I think these steps are enough for now, and let's see if there are other things to fix after that.

Thank you so much.

**Comment by chidinma-godwin** [comment]
I've changed the default case and also changed the class name of the equality sign. I was wondering if you want the operation signs to be displayed when the user clicks on it, because presently they are displayed when clicked.

**Comment by ansdb** [comment]
@chidinma-godwin Thanks a lot for your modification, if it is a good idea to hide them from being displayed in the `input-output-area` just go for it? but you need to alter the **class names** for both **numbers** and **operators**, so **numbers** class name will be `number` and **operators** class name will be `operator`, then you need to change the way numbers will be displayed, let's say the someone wants to calculate the following mathematical expression `2+3-1` the first one displayed is 2 but when clicking + and then 3 the result should appear for the first calculation which is **2+3** => **5** when clicking none numbers which are operators and in this case, it's a **minus sign** (_subtraction operation_). I hope you understand what I mean by that.

**Comment by ansdb** [comment]
Hi @chidinma-godwin I will merge your changes, for now, then I will implement the other features myself, thanks a lot for your contribution I really appreciate that you make a huge effort so far.

**Pull request merged**
